### ISSUE TITLE
error: new qq.maps.Marker({position: placeMark.resPoint, map: me.map}) 

### ISSUE THREAD

**Issue by jecyhw** [cipchk/angular-qq-maps#1]
me = this;
![image](https://user-images.githubusercontent.com/10094084/35101392-59a59c48-fc9a-11e7-85dd-007d7ca681dc.png)
how to solve it?

**Comment by cipchk** [comment]
how can I help you????

Please provider more information.

**Comment by jecyhw** [comment]
i found the problem, becase i import 'http://map.qq.com/api/js' twice, thank you.
