### ISSUE TITLE
想请问下，1.x版本是不是没有地图dragend事件的监听返回？

### ISSUE THREAD

**Issue by acegank** [cipchk/angular-qq-maps#2]
监听后一直返回undefined

**Comment by acegank** [comment]
2.x试了下，返回也是undefined

**Comment by cipchk** [comment]
麻烦提供重现示例。https://stackblitz.com/edit/angular-qq-maps

**Comment by acegank** [comment]
将qq.maps.event.addListener(this.map, 'click', (event: any)监听的click事件改成dragend，官方文档有拖拽地图后的事件
