### ISSUE TITLE
使用时提示qq is not defined

### ISSUE THREAD

**Issue by vinceok** [cipchk/angular-qq-maps#3]
new qq.maps.LatLng不报错，但是new qq.maps.Label报错，报错信息是qq is not defined，感觉像是地图js没注入，很诡异，求助！

**Comment by cipchk** [comment]
建议在 `ready` 以后再做有关于 `qq.*` 的操作。

**Comment by vinceok** [comment]
谢谢解答，现在碰到的问题是异步请求获得楼盘后，想通过label显示在地图上，但是没效果，直接在ready里设置静态label才有效，这有何办法吗？

**Comment by cipchk** [comment]
angular-qq-maps 是异步加载地图脚本，除了在 `ready` 事件才开始处理业务别无办法。
